name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2.2.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build & test
        run: docker-compose build

